# CircleCI environment variables needed:
# AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY,
# AWS_DEFAULT_REGION (eu-north-1),
# PROJECT_NAME (booking)

version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.1.3

executors:
  terraform:
    machine:
      image: ubuntu-2204:2024.04.4
  node:
    docker:
      - image: cimg/node:20.11.0

jobs:

  check_codebase_quality:
    executor: node
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

  init_update_infrastructure:
    executor: terraform
    resource_class: medium
    environment:
      AWS_CONFIG_FILE: /home/circleci/project/config
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: booking-terraform
      - configure_aws_credentials
      - run:
          name: Check AWS Infrastructure Changes
          command: |
            set -ex
            if git diff --name-status HEAD^ HEAD | grep -q terraform; then
              echo "Terraform files changed, infrastructure update needed"
              echo 'export update_infra=true' >> $BASH_ENV
            else
              echo "No terraform changes detected"
              echo 'export update_infra=false' >> $BASH_ENV
            fi
      - run:
          name: Initialize/Update AWS Infrastructure
          command: |
            set -ex
            if [[ "$update_infra" == "true" ]]; then
              wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
              echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
              sudo apt update && sudo apt install terraform=1.8.*

              cd .terraform_files/
              terraform init
              terraform workspace select -or-create=true ${CIRCLE_BRANCH}
              terraform plan -input=false -var-file=environments/${CIRCLE_BRANCH}.tfvars
              terraform apply -auto-approve -var-file=environments/${CIRCLE_BRANCH}.tfvars
            fi

  build_codebase:
    executor: node
    resource_class: medium
    environment:
      AWS_CONFIG_FILE: /home/circleci/project/config
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: booking-terraform
      - configure_aws_credentials
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Pull environment variables
          command: |
            set -ex
            aws secretsmanager get-secret-value \
              --profile booking-terraform \
              --secret-id "${CIRCLE_BRANCH}/${PROJECT_NAME}/frontend" \
              --region $AWS_DEFAULT_REGION | jq -r '.SecretString' | \
              jq -r "to_entries|map(\"\(.key)=\\\"\(.value|tostring)\\\"\")|.[]" | sed -e 's/"//' -e 's/"$//g' > .env || echo "No environment variables found"
      - run:
          name: Build codebase
          command: |
            set -ex
            export $(cat .env | grep -v '#' | awk '/=/ {print $1}');
            CI=false npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - ./

  deploy_the_application:
    executor: node
    resource_class: small
    environment:
      AWS_CONFIG_FILE: /home/circleci/project/config
    steps:
      - attach_workspace:
          at: ./
      - aws-cli/setup:
          profile_name: booking-terraform
      - configure_aws_credentials
      - run:
          name: Deploy codebase to AWS S3
          command: |
            set -ex
            # Get CloudFront Distribution ID by origin name
            cloudfront_name=${CIRCLE_BRANCH}-${PROJECT_NAME}-codebase
            export AWS_CLOUD_FRONT_ID=$(aws cloudfront list-distributions \
              --profile booking-terraform | \
              jq --arg cfname "$cloudfront_name" \
              '.DistributionList.Items[] | select(.DefaultCacheBehavior.TargetOriginId | test($cfname)) | .Id' | \
              sed 's/"//g')

            # Sync dist/ to S3
            cd ./dist && aws s3 sync . s3://${CIRCLE_BRANCH}-${PROJECT_NAME}-codebase --delete --profile booking-terraform

            # Invalidate CloudFront cache
            AWS_MAX_ATTEMPTS=10 aws cloudfront create-invalidation \
              --profile booking-terraform \
              --distribution-id "$AWS_CLOUD_FRONT_ID" \
              --paths "/*"

commands:
  configure_aws_credentials:
    steps:
      - run:
          name: Create AWS Config File
          command: |
            echo \
            "[profile booking-terraform]
            aws_access_key_id=$AWS_ACCESS_KEY_ID
            aws_secret_access_key=$AWS_SECRET_ACCESS_KEY
            region=$AWS_DEFAULT_REGION
            output=json" > config

workflows:
  deploy:
    jobs:
      - check_codebase_quality
      - init_update_infrastructure:
          filters:
            branches:
              only:
                - main
      - build_codebase:
          filters:
            branches:
              only:
                - main
      - deploy_the_application:
          requires:
            - build_codebase
            - init_update_infrastructure
          filters:
            branches:
              only:
                - main
